### ISSUE TITLE
Cant print full output of some commands

### ISSUE THREAD

**Issue by nomad0812** [buckyroberts/Python-Reverse-Shell#15] opened 2016-01-02 22:56 UTC
When executing commands like help from the server to a client on a windows machine, the command is output is not fully printed, basically any extremely long output commands are not fully printed

**Comment by N-faycal** [comment] 2016-01-02 23:09
will be resolved tonight.
This may be a duplicate of bug #13

**Comment by N-faycal** [comment] 2016-01-02 23:32
not related. It is due to the buffering. Working on it

**Comment by N-faycal** [comment] 2016-01-03 01:53
Closed. Thanks for reporting

**Closed as completed** 2016-01-03 01:53 UTC
Labels: bug
